### ISSUE TITLE
Not getting intellisense from workspace files

### ISSUE THREAD

**Issue by manikantag** [dlvhdr/typescript-lsp-poc#1]
Hi,

I'm also doing a POC to integrate monaco-editor to support TypeScript. I tried out-of-box monaco Web worker language service, but it the perf is very poor when I load 2000 `.ts` models (more on this here: https://stackoverflow.com/questions/73936684/performant-way-to-load-2000-ts-models-into-monaco-editor-for-intellisense).

Now I'm trying to see if running language server in its own process makes it any better. I came across your POC, but I can't see intellsense from the files in workspace (ex: I've added `dummy()` to `statics/pages/test.ts` but I can't get that in auto complete in `pages/home.ts`)

I updated below npm modules to latest ones:

client:
- @codingame/monaco-jsonrpc  =>  vscode-ws-jsonrpc 2.0.0
- monaco-editor 0.33.0  =>  monaco-editor 0.34.0
- monaco-editor-workers 0.33.0  =>  0.34.0
- monaco-languageclient 2.0.2  =>  4.0.0

server:
- @codingame/monaco-jsonrpc  =>  vscode-ws-jsonrpc 2.0.0
- typescript-language-server 0.10.1  =>  typescript-language-server 2.0.0
- ws 8.6.0  =>  ws 8.9.0

I fixed all compatibility issue with new versions, especially monaco-languageclient ESM upgrade caused major issue.

But still I don't see auto complete from the workspace files. 

Am I missing something? Any help is much appreciated. Thanks

**Comment by dlvhdr** [comment]
Hey @manikantag, where can I take a look at your code?
I'm not sure at which state I left this POC, so let me check.

**Comment by dlvhdr** [comment]
@manikantag I merged the latest code I had and things seem to work now.
I think the main stuff that was added were the `uriConverters`.
Test it now.

**Comment by manikantag** [comment]
Hi, thanks for taking time to update the project. I highly appreciate your help. However, I'm not getting any autocomplete when I tried. 

Steps I followed:

```
cd typescript-lsp-poc
npm i
npm run build

npm run start-server

cd packages/client
npm run webpack:build
npm run webpack:start
```

Changes I had to do:

1. remove wix related dependency from statics/package.json. Otherwise build is failing to get wix hosted dependencies from your local server.
2. delete package-lock.json & yarn.lock files due to above issue
3. fix `client/webpack/index.html` code with `client/index.html`. Otherwise getting missing DOM elements (ex: #tabs, ...)

Now able to bring up the server & client. But I'm not getting intellisense from the workspace files (like pages/) and getting some path related error in the monaco editor.

![image](https://user-images.githubusercontent.com/317299/195637599-87da12c6-ef9c-4849-bdd7-382809d5e4b0.png)

Not sure if this is because the changes I have done though.

Thanks.

**Comment by dlvhdr** [comment]
Hmm can you try running `npm run dev` from the root instead of the webpack commands? Run the server as you already did.

**Comment by manikantag** [comment]
I tried `npm run dev`, but still same issue. I'm seeing some URI issues in console

![image](https://user-images.githubusercontent.com/317299/195761373-e16eee07-0c9a-46d3-952b-bf27cd38db97.png)

I don't think this is because of my edits mentioned earlier. Thanks

**Comment by manikantag** [comment]
Not sure why the trailing `\` in model URI

**Comment by dlvhdr** [comment]
Hmm that's really weird, you have forward slash `\` in your paths instead of `/`. Are you using windows maybe?

**Comment by manikantag** [comment]
Yes, windows 10.

**Comment by dlvhdr** [comment]
I pushed a potential fix to `main`. It uses `monaco.Uri.path` instead of `fsPath` as the latter uses the platform specific path separators.

**Comment by manikantag** [comment]
Hi @dlvhdr , thanks for trying to help with your fixes. I'm on vacation, just back to work.

Unfortunately still I'm not getting code completion and the path issue is still there.

![image](https://user-images.githubusercontent.com/317299/198303566-2af664cd-a57a-4b0c-a435-d27c9c857c7b.png)
